"use client";
import {useEffect,useState} from "react";
import {createSupabaseBrowserClient} from "@/lib/supabase/browser";
import {AdminStoreNav} from "@/components/admin-store-nav";
type R={id:string;name_ar:string;slug:string;price:number;compare_at_price:number|null;is_active:boolean};
export default function Bundles(){const s=createSupabaseBrowserClient();const [rows,setRows]=useState<R[]>([]);const [f,setF]=useState({name_ar:"",name_en:"",slug:"",description_ar:"",price:"",compare:""});const [msg,setMsg]=useState("");
async function load(){const {data,error}=await s.from("store_bundles").select("*").order("created_at",{ascending:false});if(error)setMsg("تعذر تحميل الباقات");else setRows(data??[])}useEffect(()=>{load()},[]);
async function add(e:React.FormEvent){e.preventDefault();const p=Number(f.price),c=f.compare?Number(f.compare):null;if(!f.name_ar.trim()||!f.slug.trim()||!Number.isFinite(p)||p<0||(c!==null&&(!Number.isFinite(c)||c<p))){setMsg("تحقق من اسم الباقة والرابط والأسعار.");return}const {error}=await s.from("store_bundles").insert({name_ar:f.name_ar.trim(),name_en:f.name_en.trim()||f.name_ar.trim(),slug:f.slug.trim(),description_ar:f.description_ar.trim()||null,price:p,compare_at_price:c,is_active:false});if(error)setMsg("تعذر إنشاء الباقة.");else{setF({name_ar:"",name_en:"",slug:"",description_ar:"",price:"",compare:""});load()}}
async function toggle(r:R){const {error}=await s.from("store_bundles").update({is_active:!r.is_active,updated_at:new Date().toISOString()}).eq("id",r.id);if(error)setMsg("تعذر تحديث الحالة");else load()}
return <main><AdminStoreNav/><section className="storefront-section"><div className="container"><div className="page-heading"><span>إدارة المتجر</span><h1>الباقات</h1><p>إدارة الباقات الفعلية دون إنشاء عروض وهمية.</p></div><form onSubmit={add} className="admin-form"><input required placeholder="اسم الباقة" value={f.name_ar} onChange={e=>setF({...f,name_ar:e.target.value})}/><input placeholder="الاسم بالإنجليزية" value={f.name_en} onChange={e=>setF({...f,name_en:e.target.value})}/><input required placeholder="slug" value={f.slug} onChange={e=>setF({...f,slug:e.target.value})}/><textarea placeholder="الوصف" value={f.description_ar} onChange={e=>setF({...f,description_ar:e.target.value})}/><input required type="number" min="0" step="0.01" placeholder="السعر" value={f.price} onChange={e=>setF({...f,price:e.target.value})}/><input type="number" min="0" step="0.01" placeholder="السعر قبل الخصم" value={f.compare} onChange={e=>setF({...f,compare:e.target.value})}/><button className="primary-btn">إضافة باقة</button></form>{msg&&<p className="form-error">{msg}</p>}<div className="catalog-grid">{rows.map(r=><article className="catalog-card" key={r.id}><strong>{r.name_ar}</strong><p>{Number(r.price).toLocaleString("ar-SA")} SAR</p><span>{r.is_active?"منشورة":"مسودة"}</span><button className="text-link" onClick={()=>toggle(r)}>{r.is_active?"إيقاف":"نشر"}</button></article>)}</div></div></section></main>