"use client";

import { useEffect,useState } from "react";
import { createSupabaseBrowserClient } from "@/lib/supabase/browser";

type Props={params:Promise<{id:string}>};
type Cat={id:string;name_ar:string};
type Img={id:string;image_url:string;alt_ar:string|null;sort_order:number};
export default function ProductEditor({params}:Props){
 const [id,setId]=useState("");const [cats,setCats]=useState<Cat[]>([]);const [selected,setSelected]=useState<string[]>([]);const [images,setImages]=useState<Img[]>([]);const [f,setF]=useState({name_ar:"",name_en:"",slug:"",sku:"",description_ar:"",price:"",compare_at_price:"",stock_quantity:"0",brand_id:""});const [brands,setBrands]=useState<{id:string;name_ar:string}[]>([]);const [imageUrl,setImageUrl]=useState("");const [msg,setMsg]=useState("");
 const s=createSupabaseBrowserClient();
 useEffect(()=>{params.then(p=>{setId(p.id);load(p.id)})},[]);
 async function load(pid:string){const [p,c,b,i,pc]=await Promise.all([s.from("store_products").select("*").eq("id",pid).single(),s.from("store_categories").select("id,name_ar").eq("is_active",true).order("name_ar"),s.from("store_brands").select("id,name_ar").eq("is_active",true).order("name_ar"),s.from("store_product_images").select("id,image_url,alt_ar,sort_order").eq("product_id",pid).order("sort_order"),s.from("store_product_categories").select("category_id").eq("product_id",pid)]);if(p.error){setMsg("تعذر تحميل المنتج");return}const x=p.data;setF({name_ar:x.name_ar,name_en:x.name_en,slug:x.slug,sku:x.sku||"",description_ar:x.description_ar||"",price:String(x.price),compare_at_price:x.compare_at_price==null?"":String(x.compare_at_price),stock_quantity:String(x.stock_quantity),brand_id:x.brand_id||""});setCats(c.data??[]);setBrands(b.data??[]);setImages(i.data??[]);setSelected((pc.data??[]).map(x=>x.category_id))}
 async function save(e:React.FormEvent){e.preventDefault();setMsg("");const payload={name_ar:f.name_ar.trim(),name_en:f.name_en.trim()||f.name_ar.trim(),slug:f.slug.trim(),sku:f.sku.trim()||null,description_ar:f.description_ar.trim()||null,price:Number(f.price),compare_at_price:f.compare_at_price?Number(f.compare_at_price):null,stock_quantity:Math.max(0,Math.floor(Number(f.stock_quantity))),brand_id:f.brand_id||null,updated_at:new Date().toISOString()};if(!payload.name_ar||!payload.slug||!Number.isFinite(payload.price)||payload.price<0||payload.compare_at_price!==null&&(!Number.isFinite(payload.compare_at_price)||payload.compare_at_price<payload.price)){setMsg("تحقق من اسم المنتج والرابط والأسعار والمخزون.");return}const {error}=await s.from("store_products").update(payload).eq("id",id);if(error){setMsg("تعذر حفظ المنتج");return}await s.from("store_product_categories").delete().eq("product_id",id);if(selected.length)await s.from("store_product_categories").insert(selected.map(category_id=>({product_id:id,category_id})));setMsg("تم حفظ المنتج")}
 async function addImage(){if(!imageUrl.trim())return;const {error}=await s.from("store_product_images").insert({product_id:id,image_url:imageUrl.trim(),sort_order:images.length});if(error)setMsg("تعذر إضافة الصورة");else{setImageUrl("");load(id)}}
 async function removeImage(imgId:string){const {error}=await s.from("store_product_images").delete().eq("id",imgId);if(error)setMsg("تعذر حذف الصورة");else load(id)}
 return <main><section className="storefront-section"><div className="container"><div className="page-heading"><span>إدارة المنتج</span><h1>تعديل المنتج</h1></div>{msg&&<p className="form-error">{msg}</p>}<form onSubmit={save} className="admin-form"><input required placeholder="اسم المنتج بالعربية" value={f.name_ar} onChange={e=>setF({...f,name_ar:e.target.value})}/><input placeholder="الاسم بالإنجليزية" value={f.name_en} onChange={e=>setF({...f,name_en:e.target.value})}/><input required placeholder="slug" value={f.slug} onChange={e=>setF({...f,slug:e.target.value})}/><input placeholder="SKU" value={f.sku} onChange={e=>setF({...f,sku:e.target.value})}/><select value={f.brand_id} onChange={e=>setF({...f,brand_id:e.target.value})}><option value="">بدون علامة تجارية</option>{brands.map(b=><option value={b.id} key={b.id}>{b.name_ar}</option>)}</select><textarea placeholder="الوصف" value={f.description_ar} onChange={e=>setF({...f,description_ar:e.target.value})}/><input required type="number" min="0" step="0.01" placeholder="السعر" value={f.price} onChange={e=>setF({...f,price:e.target.value})}/><input type="number" min="0" step="0.01" placeholder="السعر قبل الخصم" value={f.compare_at_price} onChange={e=>setF({...f,compare_at_price:e.target.value})}/><input required type="number" min="0" step="1" placeholder="المخزون" value={f.stock_quantity} onChange={e=>setF({...f,stock_quantity:e.target.value})}/><div><strong>الفئات</strong>{cats.map(c=><label key={c.id} className="check-row"><input type="checkbox" checked={selected.includes(c.id)} onChange={e=>setSelected(e.target.checked?[...selected,c.id]:selected.filter(x=>x!==c.id))}/>{c.name_ar}</label>)}</div><button className="primary-btn">حفظ التغييرات</button></form><div className="admin-panel"><h2>صور المنتج</h2><div className="admin-form"><input type="url" placeholder="رابط الصورة الحقيقي" value={imageUrl} onChange={e=>setImageUrl(e.target.value)}/><button className="primary-btn" onClick={addImage}>إضافة صورة</button></div><div className="catalog-grid">{images.map(i=><article className="catalog-card" key={i.id}><img src={i.image_url} alt={i.alt_ar||f.name_ar}/><button className="text-link" onClick={()=>removeImage(i.id)}>حذف الصورة</button></article>)}</div></div></div></section></main>
}